org: jhonorte7
service: api-s3

provider:
  name: aws
  runtime: python3.13	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::758494286180:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      -http:
          path: /s3/crear_bucket
          method: post
          cors: true
          integration: lambda
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear_directorio
          method: post
          cors: true
          integration: lambda
  subir_archivo:
    handler: subir_archivo.lambda.handler
    events:
      - http:
          path: /s3/bucket/directorio/subir_archivo
          method: post
          cors: true
          integration: lambda
